### ISSUE TITLE
./node_modules/.bin/slack-verify No such file or directory

### ISSUE THREAD

**Issue by achen2017** [slackapi/node-slack-events-api#48]
### Description

Thanks for putting this together guys! Can't wait to get this app up and running. 

The problem: 
In Step 1 of Configuration I run a command like: 
./node_modules/.bin/slack-verify --token NcWHlwaohAHWNwerljWQRd [--path=/slack/events] [--port=3000]

but get the following error:
 -bash: ./node_modules/.bin/slack-verify: No such file or directory

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [ ] question
- [x] documentation related
- [ ] testing related
- [ ] discussion

### Requirements
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-events-api/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:
slack-events version: 
node version: v6.9.2
OS version(s): 10.12.3

#### Steps to reproduce:

1. git clone repository to a directory and run npm install --save @slack/events-api
2. ./node_modules/.bin/slack-verify --token AcDFolkkhAHoqGHxHtiaBQRd [--path=/slack/events] [--port=3000]

#### Expected result:

something that wasn't an error

#### Actual result:

/slack-verify --token AcDFolkkhAHoqGHxHtiaBQRd [--path=/slack/events] [--port=3000]
-bash: ./node_modules/.bin/slack-verify: No such file or directory

Thanks!

**Comment by aoberoi** [comment]
hey @achen2017, thanks for describing your issue so carefully.

a couple comments:
*  cloning *this* repository and running `npm install` in the directory isn't how the package is intended to be used. sorry if that wasn't clear. instead, in a project directory (or you could do this inside the `examples/greet-and-react` directory provided) you would run `npm install`. the result is npm would create the `./node_modules/.bin/slack-verify` file, and then you'd be able to run the command.
*  the part: `[--path=/slack/events] [--port=3000]` should not literally be in the command. the `[]` syntax is meant to denote that the argument is optional, and the value when you choose not to specify it would be what comes after the `=`. so if you are fine with those values, you leave them out completely and just run `./node_modules/.bin/slack-verify --token xxxxx`.
*  i'd advise you to please regenerate your verification token. its meant to be a value that is secret, but since you just shared it on this issue, its a good precaution to regenerate it (which will invalidate the old one).
