### ISSUE TITLE
Example does not work (local machine and glitch) 

### ISSUE THREAD

**Issue by sidbav** [slackapi/node-slack-events-api#73]
### Description

Describe your issue here.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [x] question
- [x] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-events-api/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report
When I run the greet and react example on my local machine or on glitch i end up getting errors on both. Both of the files are glitch and the example on github are different (atleast the .env files and package.json is as well, not sure about  are not the same either so I am not sure if I am running into an error 

#### Local Machine
`@slack/events-api` version: 2.0.0
#### Glitch
`@slack/events-api` version: 1.0.0

#### Local Machine
node version: v10.1.0
#### Glitch
node version: v8.11.3

OS version(s): Microsoft Windows [Version 10.0.17134.228]

#### Local Machine
1. `git clone https://github.com/slackapi/node-slack-events-api.git`
2.  `cd example/greet-and-react`
3. `npm i`
4. rename .env.sample to .env
5. fill in info in the .env file
6. `node index.js`
#### Expected result: 

What you expected to happen
- program runs

#### Actual result:

What actually happened
brings up an error (see below)

 #### Glitch
1. Fill in info in .env file (which btw are not the same in the repo and the file)
2. Go to your slack app (create on if you haven't already) 
3. Go to the events subscription section, fill in your glitch url +` /slack/events`

#### Expected result: 

What you expected to happen
- Slack brings up no errors

#### Actual result:

What actually happened
slack brings up an error (see below)

##### When running on my Local Machine: 
![image](https://user-images.githubusercontent.com/35268021/44360913-4aab9100-a48a-11e8-94c6-238bc5d9ed50.png)
##### When running on Glitch: 
![image](https://user-images.githubusercontent.com/35268021/44361269-564b8780-a48b-11e8-9cb0-d104f19f8d8d.png)

I hope all this info is enough to help!

**Comment by shanedewael** [comment]
Hey Sidharth, sorry about that. The error message looks incorrect (it should say `SlackEventAdapter needs a signing secret`) and the Glitch example hasn't been updated yet. I'm working on getting them both fixed.

As for the source of the error...the latest release contained an update that replaces the verification method with request signing. As a developer, this means that you need to pass in your app's signing secret rather than the verification token you're likely passing in now. You can find your signing secret right above the verification token on the app configuration page in the "Basic Info" tab:

![image](https://user-images.githubusercontent.com/3411005/44416317-729d0200-a527-11e8-9d1d-c72c452dc391.png)

If you're still having issues after you update to your app's signing secret, let me know 😄

**Comment by shanedewael** [comment]
@sidbav Oops, when I was going through and fixing the example, I realized that the `.env` had a variable called `SLACK_SIGNING_SECRET` and in `index.js` it was passing in (an undefined) `SIGNING_SECRET`. This was what was likely causing your issue. I cleaned this up in #74.

**Comment by sidbav** [comment]
@shanedewael Thank you so much! I can't believe I did not notice that!
