### ISSUE TITLE
Greet and React Permissions

### ISSUE THREAD

**Issue by brookshelley** [slackapi/node-slack-events-api#81]
### Description

When using the example `greet and react` app, the instructions lack information on OAuth permissions for the application to read messages in a channel and respond. 

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [ ] question
- [x ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x ] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-events-api/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x ] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x ] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report
After inviting the new bot to a channel and typing "hi", my glitch application returns this error:
`No authorization found for this team. Did you install this app again after restarting?`

**Comment by aoberoi** [comment]
I'm not sure what this means. That error message happens when the server receives an event for a team/workspace for which it doesn't have an access token. Since access tokens are stored in memory (we don't have a database in glitch and setting one up externally is way too hard just to get this simple example running), this commonly occurs when you complete the OAuth to install the app in a workspace, but then make a code change, so glitch purges memory and restarts the app. The error message is supposed to hint about this possibility and simply direct you to `install the app again` as that's a quick fix for this issue (it puts the access token back in memory).

**Comment by brookshelley** [comment]
Ah yea, I misunderstood what was happening when I made this, lol. I blame the smoke.
