### ISSUE TITLE
dialog.open method to generate drop down value based on another element selected value.

### ISSUE THREAD

**Issue by nsinnakkavadi** [slackapi/node-slack-events-api#88]
### Description

I am using dialog.open method, in this there are two elements with select option, I have selected value from drop down menu in the first element, and from second element I need to select the options based on first element selected values, which is not getting in the "dialog_suggestion" payload.

Is it possible to send the selected value from the first element, before select the value from second element drop down?
### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-events-api/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

`@slack/events-api` version: 1.3.0

node version: v10.15.0

OS version(s): CentOS Linux release 7.5.1804 (Core)

#### Steps to reproduce:

1. use dialog.open method with two elements, select the value from drop down.
2. try to select the value from second drop down based on the first drop down value.
3.

#### Expected result:

I should be able to generated dynamic values based on the first element selected values.

#### Actual result:

I am not able to get the value to decide which is selected from the first element from the dialog_suggestion payload.

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

![image](https://user-images.githubusercontent.com/41138608/52054991-251bcb00-2584-11e9-8d07-667d83c53d58.png)

**Comment by aoberoi** [comment]
Sorry, this is not possible using Dialogs today. Thanks for taking the time writing us in with the feedback. We've heard from many developers who are looking for this type of functionality.

In the meantime, many developers have found Block Kit messages (either in channel or in a DM from the Bot User of an App) to be an acceptable alternative. Block Kit based messages can embed several action blocks, and each action will trigger a request to the App.

Since v1.1.1, the [`@slack/interactive-messages`](https://github.com/slackapi/node-slack-interactive-messages) package supports block actions.
